name: new_web
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number sepaFrated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  dotted_border: ^2.0.0+2
  flutter_svg: ^1.0.3
  assets_audio_player: ^3.0.4+1
  http: ^0.13.4
  path: ^1.8.0
  flutter_staggered_animations: ^1.0.0
  intl: ^0.17.0
  url_launcher: ^6.0.20
  crypto: ^3.0.1
  markdown_widget:
    git:
      url: https://github.com/asjqkkkk/markdown_widget.git
      ref: br_pre_2.0
  scrollable_positioned_list: ^0.3.5
  html: ^0.15.0
  video_player: ^2.4.10

  youtube_player_iframe: ^4.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: siyuan
      fonts:
        - asset: assets/fonts/siyuan.ttf
  assets:
   - assets/fonts/
   - assets/friend/
   - assets/game_screens/bioShockInfinite/thumbnails/
   - assets/game_screens/bioShockInfinite/
   - assets/game_screens/borderlands2/thumbnails/
   - assets/game_screens/borderlands2/
   - assets/game_screens/darkSouls3/thumbnails/
   - assets/game_screens/darkSouls3/
   - assets/game_screens/guJian3/thumbnails/
   - assets/game_screens/guJian3/
   - assets/game_screens/myTimeAtPortia/thumbnails/
   - assets/game_screens/myTimeAtPortia/
   - assets/game_screens/sekiro/thumbnails/
   - assets/game_screens/sekiro/
   - assets/game_screens/theWitcher3/thumbnails/
   - assets/game_screens/theWitcher3/
   - assets/game_screens/trine4/thumbnails/
   - assets/game_screens/trine4/
   - assets/img/
   - assets/jsons/
   - assets/music/
   - assets/svgs/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
